### ISSUE TITLE
如何参加翻译，现在全是英文，例如相关的文件如何更新

### ISSUE THREAD

**Issue by sunleonx** [moodyhunter/QvPersonal#1]

**Comment by moodyhunter** [comment]
I'm not currently interested in translating QvPersonal, will provide a translation guide in the future.

**Comment by xz-dev** [comment]
> I'm not currently interested in translating QvPersonal, will provide a translation guide once the basic feature set is stabilized.

那可以提交拥有翻译功能的补丁吗

**Comment by moodyhunter** [comment]
Yes, of course, contributions are always welcomed.
