### ISSUE TITLE
将日志单独放在一个tab页

### ISSUE THREAD

**Issue by lpxnvk** [moodyhunter/QvPersonal#11]
目前日志框实在是是太小了，每次看都需要重新拉开整个程序大小，
看到新版把系统代理开关给去掉，能不能加回来 有时候程序默认启动就是不需要系统代理

**Comment by moodyhunter** [comment]
To make the log browser larger, the current MainWindow needs to be redesigned, this takes time and is not my current focus.

The system proxy settings will be merged into the new Command Plugin. This has been stated clearly in the Release Note of a prior version, please read carefully before asking.
