### ISSUE TITLE
Dependency Qt 6.2 is so new that even manjaro can not catch up

### ISSUE THREAD

**Issue by playgithub** [moodyhunter/QvPersonal#13]
really personal

**Comment by database64128** [comment]
Use https://aur.archlinux.org/packages/qv2ray-static-bin-nightly/. And be respectful next time.

**Comment by moodyhunter** [comment]
There are always reasons to and not to use specified dependencies at specific versions:

I use Qt 6.2 for the C++ literal function `QString operator""_qs(const char16_t *str, size_t size)`, for its complete WASM support, for QtCharts and for many components that were not in Qt 6.1 (See [What's in Qt6.2](https://wiki.qt.io/New_Features_in_Qt_6.2))

The missing availability of Qt 6.2 isn't something that you should blame on me, especially there ARE solutions: installing Qt manually or use prebuilt static packages. 

You mentioned "really personal" in the issue body, which I think is to emphasize something. If that's the case, it'll be very welcomed if you want to make things clear.

**Comment by playgithub** [comment]
> Use https://aur.archlinux.org/packages/qv2ray-static-bin-nightly/. And be respectful next time.

Fine, I don't mean **personal** with any impoliteness anyway.
It's totally normal to use the most advanced version for personal use.

**Comment by playgithub** [comment]
> There are always reasons to and not to use specified dependencies at specific versions:
> 
> I use Qt 6.2 for the C++ literal function `QString operator""_qs(const char16_t *str, size_t size)`, for its complete WASM support, for QtCharts and for many components that were not in Qt 6.1 (See [What's in Qt6.2](https://wiki.qt.io/New_Features_in_Qt_6.2))
> 
> The missing availability of Qt 6.2 isn't something that you should blame on me, especially there ARE solutions: installing Qt manually or use prebuilt static packages.
> 
> You mentioned "really personal" in the issue body, which I think is to emphasize something. If that's the case, it'll be very welcomed if you want to make things clear.
> 
> You mentioned "... that even Manjaro cannot catch up..." as well, AFAIK there are already Qt6.2 packages in the ArchLinux testing repository. So, try using ArchLinux?

In fact I prefer new versions, it always take advantages.
"even Manjaro cannot catch up" just means it is very new.
"really personal" just means it matches its name, and "so new" don't means bad anyway.
It's a little harder to prepare the dependencies, but it deserves for better code.

Thanks

**Comment by GavinAndre** [comment]
你既然用的是Manjaro应该说不出even manjaro can not catch up这种话啊 Manjaro上的软件包滞后是出了名的

**Comment by playgithub** [comment]
> 你既然用的是Manjaro应该说不出even manjaro can not catch up这种话啊 Manjaro上的软件包滞后是出了名的

够新了，Qt官网首页才6.1.2
![image](https://user-images.githubusercontent.com/3665590/129865011-39126cee-690f-4587-a9b1-e9d3cff31a95.png)

我不介意更新的，更好用，就安装麻烦一点
