### ISSUE TITLE
QvPersonal has nothing change when import a vmess MD5 with aid!=0

### ISSUE THREAD

**Issue by TakoTakoo** [moodyhunter/QvPersonal#3]
This can be confusing when import vmess MD5 with aid!=0. This problem also occurs when update the subscription, vmessMD5 with none zero aid node just be removed, but has no alert. A alert window like this can be better, maybe. This window seems only appear when edit a non-zero aid vmess node.

![image](https://user-images.githubusercontent.com/85894051/125154075-b991ab00-e18a-11eb-9a09-3140ec872004.png)

**Comment by SekiBetu** [comment]
https://web.archive.org/web/20160829052958/https://github.com/breakwa11/shadowsocks-rss/issues/38
https://github.com/shadowsocks/shadowsocks-windows/issues/3059
https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E7%8E%B7%E6%B1%A1%E6%9C%BA%E5%88%B6
![image](https://user-images.githubusercontent.com/38283893/125170121-e6bc7880-e1df-11eb-86d2-2bffa97427d0.png)
Community needs to move forward.

**Comment by TakoTakoo** [comment]
I am not ask to add this deprecated method back, just a suggestion to add an obvious alert.
After all, this is not mentioned in release note.

**Comment by moodyhunter** [comment]
It's deprecated, by all mean it's not suggested to use, which means the new Qv2ray should *NOT* understand what an `alterId` means.

Let's fast forward our clock to the new year.
