### ISSUE TITLE
开启嗅探导致核心崩溃

### ISSUE THREAD

**Issue by lonble** [moodyhunter/QvPersonal#5]
1. socks和http代理的嗅探开启以后，运行一段时间，核心就会崩溃，暂时没有从核心或qv日志中发现有用的错误信息。关闭嗅探功能后一切正常
2. 任意门的嗅探开启以后，只要有数据传入，核心就会立刻崩溃。
3. 任意门的嗅探设置有bug，即使上一次保存时关闭了嗅探，重新打开首选项的时候嗅探依然会保持开启状态。

---

v2ray：4.40.1
Qv2ray：3.0.0-earlydev:6253
操作系统：Linux 5.12
安装来源：AUR

**Comment by moodyhunter** [comment]
The version labelled: "3.0.0-earlydev:6253" is not from my fork.
