### ISSUE TITLE
希望能和QV2ray 2.x同时使用

### ISSUE THREAD

**Issue by torgitor** [moodyhunter/QvPersonal#6]
目前QvPersonal还处于开发早期，需要时间完善，日常使用仍需以2.x为主力。但目前QvPersonal和2.x无法同时启动，这对于尝试QvPersonal颇为不便，建议QvPersonal改为能够与2.x同时使用，以便引导用户跟随QvPersonal逐步切换过来。

**Comment by moodyhunter** [comment]
Something happened inside the Qv2ray development team and seems the development is no longer active, as before, so I forked the repo from the latest v3 branch and started redesigning the whole product.

The codename of Qv2ray 3.0 is "Qv2ray 3.0, the new era.", which aims to be a huge change in configuration and in its UI, even the feature set (some features are removed, as you can see).

I tried to keep as many configurations entries unchanged as possible, however, with the huge changes in the separation of `Qv2rayBase` and the redesigned plugin API, there's hardly something that can be preserved.

Changes occur all the time, get ready.
