### ISSUE TITLE
软件包问题

### ISSUE THREAD

**Issue by lonble** [moodyhunter/QvPersonal#8]
在release里目前只有windows和macos的二进制包，没有Linux的。对此我有以下问题：

1. 是否打算对主流的包管理器推出特定的软件包
2. 是否打算建立AUR仓库
3. QvPersonal的构建方式与Qv2ray文档中的构建方式是否兼容，或者是否打算把QvPersonal的构建方式写到Wiki或者README

**Comment by moodyhunter** [comment]
@lonble coming soon

**Comment by moodyhunter** [comment]
I'm not interested in packaging against Linux distributions, although I'm a Linux user, however, it's always welcomed if someone provides per-distro packages.
For AUR, see above.

For compilation steps, you may want to read https://github.com/moodyhunter/QvPersonal/wiki/Compilation-Guidance

**Comment by database64128** [comment]
I'm working with @moodyhunter to have a static build packaged into AUR.

The reasons for choosing static linking and not updating the [existing package](https://aur.archlinux.org/packages/qv2ray-git/) are:

- Qt 6.2 is still in beta.
- Using system uvw is blocked by skypjack/uvw#246.
- Building Qv2rayBase with uvw supplied by the submodules causes uvw to be included in the package.

**Comment by database64128** [comment]
The AUR package has been published: https://aur.archlinux.org/packages/qv2ray-static-bin-nightly/
