### ISSUE TITLE
Option completely resetted after crash

### ISSUE THREAD

**Issue by shanoaice** [moodyhunter/QvPersonal#9]
Occasionally, trying to connect or reconnect a existing connection can cause a crash -- with no message or warning. After such crash, the whole application will reset itself and there's nothing left. All the connections and previous DNS, Rounting settings will disappear and I need to reconfigure everything.

V2Ray Core: Xray-latest (git build)
QvPersonal Version: latest (Github Action build)

**Comment by moodyhunter** [comment]
As stated clearly, when using QvPersonal with Xray, it will crash when the configuration check fails. This is an intended behavior.

The solution is straightforward: use v2ray-core.
